"""initial schema

Revision ID: 2d6ba0299cc3
Revises: 
Create Date: 2026-01-29 11:25:11.962930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d6ba0299cc3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('garmin_activity_id', sa.String(), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('avg_hr', sa.Integer(), nullable=True),
    sa.Column('max_hr', sa.Integer(), nullable=True),
    sa.Column('min_hr', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('avg_stress', sa.Integer(), nullable=True),
    sa.Column('training_effect_aerobic', sa.Float(), nullable=True),
    sa.Column('training_effect_anaerobic', sa.Float(), nullable=True),
    sa.Column('hr_zones_json', sa.JSON(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('garmin_activity_id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_start_time'), ['start_time'], unique=False)

    op.create_table('body_battery_samples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('body_battery', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('body_battery_samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_body_battery_samples_timestamp'), ['timestamp'], unique=True)

    op.create_table('daily_habits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('habit_name', sa.String(), nullable=False),
    sa.Column('habit_value', sa.String(), nullable=False),
    sa.Column('habit_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'habit_name', name='uix_habit_date_name')
    )
    with op.batch_alter_table('daily_habits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_habits_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_habits_habit_name'), ['habit_name'], unique=False)

    op.create_table('daily_summary_cache',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('heart_rate_samples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('heart_rate', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('heart_rate_samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_heart_rate_samples_timestamp'), ['timestamp'], unique=True)

    op.create_table('hrv_samples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('hrv_value', sa.Float(), nullable=False),
    sa.Column('reading_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hrv_samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hrv_samples_timestamp'), ['timestamp'], unique=True)

    op.create_table('raw_garmin_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'endpoint', name='uix_garmin_date_endpoint')
    )
    op.create_table('raw_habitsync_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('sleep_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sleep_start', sa.DateTime(), nullable=True),
    sa.Column('sleep_end', sa.DateTime(), nullable=True),
    sa.Column('total_sleep_seconds', sa.Integer(), nullable=True),
    sa.Column('deep_sleep_seconds', sa.Integer(), nullable=True),
    sa.Column('light_sleep_seconds', sa.Integer(), nullable=True),
    sa.Column('rem_sleep_seconds', sa.Integer(), nullable=True),
    sa.Column('awake_seconds', sa.Integer(), nullable=True),
    sa.Column('sleep_score', sa.Integer(), nullable=True),
    sa.Column('avg_overnight_hrv', sa.Float(), nullable=True),
    sa.Column('avg_overnight_spo2', sa.Float(), nullable=True),
    sa.Column('avg_overnight_rr', sa.Float(), nullable=True),
    sa.Column('raw_sleep_levels', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('spo2_samples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('spo2_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spo2_samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spo2_samples_timestamp'), ['timestamp'], unique=True)

    op.create_table('steps_samples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('steps_samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_steps_samples_timestamp'), ['timestamp'], unique=True)

    op.create_table('stress_samples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('stress_level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stress_samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stress_samples_timestamp'), ['timestamp'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stress_samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stress_samples_timestamp'))

    op.drop_table('stress_samples')
    with op.batch_alter_table('steps_samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_steps_samples_timestamp'))

    op.drop_table('steps_samples')
    with op.batch_alter_table('spo2_samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spo2_samples_timestamp'))

    op.drop_table('spo2_samples')
    op.drop_table('sleep_sessions')
    op.drop_table('raw_habitsync_responses')
    op.drop_table('raw_garmin_responses')
    with op.batch_alter_table('hrv_samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hrv_samples_timestamp'))

    op.drop_table('hrv_samples')
    with op.batch_alter_table('heart_rate_samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_heart_rate_samples_timestamp'))

    op.drop_table('heart_rate_samples')
    op.drop_table('daily_summary_cache')
    with op.batch_alter_table('daily_habits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_habits_habit_name'))
        batch_op.drop_index(batch_op.f('ix_daily_habits_date'))

    op.drop_table('daily_habits')
    with op.batch_alter_table('body_battery_samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_body_battery_samples_timestamp'))

    op.drop_table('body_battery_samples')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_start_time'))

    op.drop_table('activities')
    # ### end Alembic commands ###
