"""add sync_log table

Revision ID: 2f297e1ff2b9
Revises: 2d6ba0299cc3
Create Date: 2026-01-29 11:59:03.021173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f297e1ff2b9'
down_revision: Union[str, Sequence[str], None] = '2d6ba0299cc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sync_type', sa.String(), nullable=False),
    sa.Column('date_synced', sa.Date(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_log')
    # ### end Alembic commands ###
